/**
 * Settings → Briefings tab.
 *
 * Two controls:
 *   - Anthropic API key (paste/save/clear, encrypted at rest)
 *   - Preferred Claude model (device-local localStorage)
 *
 * The privacy disclosure is verbatim from ADR 019: the key is
 * encrypted at rest under the vault key, and the key + every briefing
 * payload only ever leave the browser on a call the user initiated.
 * FeedZero's servers never see the key, the prompt, or the articles.
 */

import { useEffect, useState } from "react";
import { KeyRound, Sparkles, Trash2, CheckCircle2 } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  getAnthropicKey,
  setAnthropicKey,
  clearAnthropicKey,
} from "@/core/storage/secrets";
import { useBriefingModelPreference } from "@/lib/briefing-model-preference";
import { useSignalAIHidden } from "@/lib/signal-mode-preference";
import { Switch } from "@/components/ui/switch";
import {
  BRIEFING_MODELS,
  isBriefingModelId,
} from "@/core/briefings/models";
import { toast } from "sonner";

export function BriefingsTab() {
  const [model, setModel] = useBriefingModelPreference();
  const [hasKey, setHasKey] = useState<boolean | null>(null);
  const [keyInput, setKeyInput] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    void (async () => {
      const result = await getAnthropicKey();
      setHasKey(result.ok ? result.value !== null : false);
    })();
  }, []);

  async function handleSave() {
    setSaving(true);
    const result = await setAnthropicKey(keyInput);
    setSaving(false);
    if (!result.ok) {
      toast.error(result.error);
      return;
    }
    setKeyInput("");
    setHasKey(true);
    toast.success("Anthropic API key saved");
  }

  async function handleClear() {
    const result = await clearAnthropicKey();
    if (!result.ok) {
      toast.error("Couldn't clear the key");
      return;
    }
    setHasKey(false);
    toast.success("Anthropic API key removed");
  }

  return (
    <div className="space-y-4 py-2">
      <div className="rounded-lg border border-border bg-card p-4 space-y-3">
        <div className="flex items-center gap-2">
          <KeyRound className="size-4 text-muted-foreground" />
          <p className="text-sm font-medium">Anthropic API key</p>
          {hasKey === true ? (
            <span className="flex items-baseline gap-1 text-xs text-emerald-600 dark:text-emerald-400">
              <CheckCircle2 className="size-3" />
              saved
            </span>
          ) : null}
        </div>
        <p className="text-xs text-muted-foreground">
          Briefings are generated by Anthropic&apos;s API using a key you
          supply. The key is encrypted at rest in your vault. On Refresh
          your key + the briefing payload transit FeedZero&apos;s relay
          (<code>/api/briefing</code>) on their way to{" "}
          <code>api.anthropic.com</code> — the relay forwards the bytes,
          neither logs nor persists them, and never inspects the
          contents. (The relay exists because iOS Safari blocks the
          direct browser-to-Anthropic call.) Get a key at{" "}
          <a
            href="https://console.anthropic.com/settings/keys"
            target="_blank"
            rel="noreferrer noopener"
            className="underline"
          >
            console.anthropic.com
          </a>
          .
        </p>
        <div className="flex gap-2">
          <Input
            type="password"
            placeholder="sk-ant-..."
            value={keyInput}
            onChange={(e) => setKeyInput(e.target.value)}
            autoComplete="off"
            data-1p-ignore
          />
          <Button onClick={() => void handleSave()} disabled={saving || !keyInput.trim()}>
            {saving ? "Saving..." : "Save"}
          </Button>
        </div>
        {hasKey === true ? (
          <Button
            variant="ghost"
            size="sm"
            onClick={() => void handleClear()}
            className="text-destructive hover:text-destructive"
          >
            <Trash2 className="size-4" />
            Remove stored key
          </Button>
        ) : null}
      </div>

      <div className="rounded-lg border border-border bg-card p-4 space-y-3">
        <div className="flex items-center gap-2">
          <Sparkles className="size-4 text-muted-foreground" />
          <p className="text-sm font-medium">Preferred model</p>
        </div>
        <p className="text-xs text-muted-foreground">
          Picks which Claude model your briefings use. You pay Anthropic
          per token — match the model to your budget and quality
          tradeoff. This preference is stored on this device only.
        </p>
        <div className="space-y-2">
          {BRIEFING_MODELS.map((m) => (
            <label
              key={m.id}
              className={
                "flex cursor-pointer items-start gap-3 rounded border p-3 transition-colors " +
                (m.id === model
                  ? "border-primary bg-primary/5"
                  : "border-border hover:bg-accent")
              }
            >
              <input
                type="radio"
                name="briefing-model"
                value={m.id}
                checked={m.id === model}
                onChange={(e) => {
                  const v = e.target.value;
                  if (isBriefingModelId(v)) setModel(v);
                }}
                className="mt-0.5"
              />
              <div className="space-y-0.5">
                <p className="text-sm font-medium">{m.label}</p>
                <p className="text-xs text-muted-foreground">{m.description}</p>
              </div>
            </label>
          ))}
        </div>
      </div>

      <SignalAIHiddenPanel />
    </div>
  );
}

function SignalAIHiddenPanel() {
  const [hidden, setHidden] = useSignalAIHidden();
  return (
    <div className="rounded-lg border border-border bg-card p-4 space-y-3">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <p className="text-sm font-medium">Hide AI Signal mode</p>
          <p className="mt-1 text-xs text-muted-foreground">
            Removes the AI/Local toggle from the Signal page. Use this if
            you only want the on-device frequency engine ever — no LLM,
            no Anthropic calls. Flipping this on also forces the current
            mode back to Local.
          </p>
        </div>
        <Switch
          checked={hidden}
          onCheckedChange={setHidden}
          aria-label="Hide AI Signal mode"
        />
      </div>
    </div>
  );
}
